import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [],
  template: `
    <h1 style="position: sticky; top: 0; right: 0; background-color: white;padding: 1rem; border-bottom: 1px solid black;">Welcome to {{title}}!</h1>

    <div style="margin-top: 3rem;">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mi diam, iaculis eu massa vitae, commodo gravida sapien. Cras tincidunt mi et turpis sagittis laoreet. Morbi ut augue pharetra, dictum est et, egestas nisl. Fusce dignissim lectus a est pulvinar aliquet. Fusce blandit, metus id blandit malesuada, leo sapien scelerisque sem, at posuere quam dui at turpis. Nulla pellentesque est nulla, id malesuada tellus rutrum in. Nulla semper dictum quam at pellentesque. Aenean ac aliquam metus, ac placerat ipsum. Nullam sit amet lorem eget arcu fermentum bibendum at sollicitudin lacus. Sed ullamcorper laoreet mauris, sit amet tempus erat pulvinar et. Sed venenatis tellus nibh, posuere sagittis libero luctus non. Praesent tempor sapien at rhoncus venenatis.</p>

      <p>Praesent tempor ex id quam pretium, sit amet vestibulum est pharetra. Mauris a dolor lacus. Sed ac felis ipsum. Aliquam eu lacinia velit, gravida volutpat nunc. Nulla nec dapibus ligula, porta elementum justo. Proin vel ipsum tellus. Donec sollicitudin eget mi vitae venenatis. Aliquam lorem nunc, mattis ac nisi vitae, vulputate pharetra velit.</p>

      <p>Suspendisse vitae felis odio. Donec dignissim nisl eget risus tempus, ac convallis tellus fermentum. Nam sit amet efficitur sapien. In id augue a nisi rhoncus congue. Sed quis neque non tortor viverra hendrerit. Sed sed elementum ligula. Praesent elementum nisi enim, consequat pharetra eros bibendum sed. Sed non bibendum libero. Nulla a quam ante. Nam at orci urna.</p>

      <p>Suspendisse mattis nisi interdum velit tincidunt lacinia. Suspendisse luctus urna nec lobortis laoreet. Donec sed accumsan ipsum. Vivamus ut eleifend nibh. Fusce sit amet ullamcorper erat. Aliquam accumsan auctor metus, quis tincidunt nunc volutpat nec. Vivamus vulputate est in blandit aliquam. Donec mi ante, efficitur sit amet posuere eu, molestie et purus.</p>

      <p>Aliquam eget ante quis nisl rutrum sollicitudin. Aliquam vestibulum, dolor ac mattis aliquam, ipsum nibh commodo elit, quis blandit elit erat vitae est. Nam lobortis enim vel accumsan feugiat. Cras rutrum interdum metus, in dignissim velit sollicitudin eu. Nullam id ipsum vel felis tristique egestas quis eget est. Nunc non justo et arcu porta consequat et ac elit. Phasellus ut eleifend neque, non vulputate sem. Ut leo eros, fermentum ut orci scelerisque, scelerisque dignissim nisi. Sed lobortis purus ligula, eu molestie dui varius vel.</p>

      <p>Donec id faucibus purus. Nulla non purus sit amet augue blandit dignissim. Suspendisse viverra turpis turpis, eu lacinia ex sagittis nec. Sed et nibh ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a purus tempus, consectetur quam in, lacinia sem. Praesent vitae metus faucibus, finibus lorem non, pulvinar neque. Integer ornare eget mauris a malesuada. Suspendisse non fermentum turpis. Nam sit amet sapien vestibulum tortor laoreet placerat in semper arcu. Etiam est neque, commodo et imperdiet eget, fringilla id nulla. Etiam vitae fringilla leo, ut tempus lectus.</p>

      <p>Sed et risus lobortis, accumsan mauris ut, bibendum nisi. Proin molestie bibendum tellus, sit amet pharetra nulla sollicitudin a. Nulla eget ullamcorper diam, id consectetur eros. Donec ac rutrum mi. Donec suscipit augue ac quam ultricies suscipit. Fusce blandit consequat arcu. Nam gravida ligula et convallis tempus.</p>

      <p>Pellentesque facilisis euismod laoreet. Curabitur tellus elit, vulputate a ligula quis, varius tempus justo. Nam cursus, tortor at vestibulum feugiat, justo justo elementum metus, nec tristique neque velit pharetra velit. Curabitur quam libero, fermentum quis efficitur quis, ornare eget ante. Vivamus venenatis tortor in ante dapibus pellentesque. Phasellus ut nulla ut sem tincidunt lobortis quis vitae turpis. Donec sodales, tellus vel pulvinar dapibus, erat nisi feugiat dolor, eu faucibus nulla turpis ut tortor. Mauris mollis, massa id tristique luctus, lorem nibh venenatis nisi, eu finibus nunc sem vitae dui. Nam ut venenatis magna, facilisis sagittis magna. Donec non interdum nibh. Integer commodo, sem quis placerat cursus, tellus erat vestibulum magna, non semper dui ipsum non mauris. Maecenas volutpat felis dolor, consequat aliquam eros facilisis sodales. Nullam iaculis finibus quam, sit amet ultrices tellus vestibulum eget.</p>

      <p>Duis dictum felis vel lorem tempor, eu ultricies erat dapibus. Duis elit orci, pretium in finibus sit amet, pretium at velit. Sed tincidunt sem non vulputate bibendum. Donec eleifend aliquet enim ac dapibus. Suspendisse iaculis nisi quis justo imperdiet, eget efficitur felis tristique. Aliquam viverra ante ac metus feugiat, a tempus lorem luctus. In hac habitasse platea dictumst. Mauris a quam leo.</p>

      <p>Nam aliquet pulvinar velit, sed imperdiet nisl pulvinar a. Morbi porta varius quam, nec aliquet nisi egestas nec. Ut lobortis vehicula metus in pharetra. Sed sed vulputate velit. Donec ultricies mauris at magna tempus consectetur. Morbi ac dapibus enim, fringilla feugiat metus. Maecenas vestibulum, libero nec imperdiet interdum, turpis metus ullamcorper libero, quis maximus neque diam sit amet sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In a purus consequat, bibendum nunc sagittis, interdum augue. Sed interdum aliquam velit, sit amet tincidunt metus euismod id.</p>

      <p>Proin ut pretium ligula. Etiam sit amet eleifend leo. Curabitur feugiat dapibus tortor ac condimentum. Proin quis porta nunc. Mauris in iaculis est. Duis consectetur, magna non malesuada tempus, neque orci lobortis massa, at mollis massa neque a lacus. Vivamus ac mauris sed ligula vestibulum placerat. Morbi vitae condimentum sem. Morbi fermentum feugiat nulla nec porta. Aliquam ornare at ex eu congue.</p>

      <p>Nam mauris nulla, vehicula eu mi a, porta scelerisque tellus. Pellentesque vehicula iaculis blandit. Sed pulvinar auctor odio. Praesent venenatis ante sit amet neque lobortis, sit amet fermentum mi faucibus. Sed vel porttitor augue. Donec ultrices pellentesque laoreet. Suspendisse sed purus est. Sed tempus lacus tincidunt dolor scelerisque semper. Suspendisse eu tempus urna. Nam vitae ligula consectetur, viverra leo a, molestie lectus.</p>

      <p>Proin cursus arcu sed sem posuere, semper rutrum orci placerat. Integer commodo ipsum quis orci imperdiet euismod. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec et erat non ante bibendum viverra. Nullam sit amet accumsan mi. Donec a ligula et tellus aliquam euismod quis tempus felis. Quisque vel nibh iaculis, eleifend massa vitae, laoreet metus. Nunc quis nisi metus. Curabitur ac felis leo. Ut rhoncus, nibh nec elementum semper, ligula sem imperdiet magna, ac euismod felis nulla tempus ligula. Sed pharetra nulla in elit ullamcorper scelerisque. Duis purus est, auctor et dictum at, fringilla et dui. Etiam imperdiet finibus facilisis. Donec vestibulum nibh non massa pulvinar tempor. Aliquam euismod maximus tellus porttitor auctor.</p>

      <p>Proin feugiat, erat eget molestie rutrum, est velit congue mauris, vitae posuere velit ipsum in ante. In egestas placerat ex, sed tempor leo. Cras vel suscipit est. Cras convallis erat vitae felis bibendum posuere. Quisque ornare maximus nisl vitae dignissim. Quisque quis blandit dui. Vestibulum at egestas erat. Curabitur egestas enim nisi, ac ultrices ligula bibendum quis. Proin congue feugiat odio, eu cursus lectus faucibus eu. Morbi quis purus eu mi vestibulum faucibus et id purus.</p>

      <p>Nunc et mi bibendum nibh tristique iaculis. Sed sollicitudin ornare imperdiet. Mauris aliquet vehicula est, nec laoreet neque posuere ac. Nullam a ornare nunc. Ut faucibus lectus a urna pellentesque, ut mollis felis molestie. Vestibulum vulputate mauris ut molestie egestas. Suspendisse posuere eget est et tincidunt. Nunc nec feugiat orci. Donec enim massa, faucibus vel tellus pulvinar, semper sagittis diam.</p>

      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mi diam, iaculis eu massa vitae, commodo gravida sapien. Cras tincidunt mi et turpis sagittis laoreet. Morbi ut augue pharetra, dictum est et, egestas nisl. Fusce dignissim lectus a est pulvinar aliquet. Fusce blandit, metus id blandit malesuada, leo sapien scelerisque sem, at posuere quam dui at turpis. Nulla pellentesque est nulla, id malesuada tellus rutrum in. Nulla semper dictum quam at pellentesque. Aenean ac aliquam metus, ac placerat ipsum. Nullam sit amet lorem eget arcu fermentum bibendum at sollicitudin lacus. Sed ullamcorper laoreet mauris, sit amet tempus erat pulvinar et. Sed venenatis tellus nibh, posuere sagittis libero luctus non. Praesent tempor sapien at rhoncus venenatis.</p>

      <p>Praesent tempor ex id quam pretium, sit amet vestibulum est pharetra. Mauris a dolor lacus. Sed ac felis ipsum. Aliquam eu lacinia velit, gravida volutpat nunc. Nulla nec dapibus ligula, porta elementum justo. Proin vel ipsum tellus. Donec sollicitudin eget mi vitae venenatis. Aliquam lorem nunc, mattis ac nisi vitae, vulputate pharetra velit.</p>

      <p>Suspendisse vitae felis odio. Donec dignissim nisl eget risus tempus, ac convallis tellus fermentum. Nam sit amet efficitur sapien. In id augue a nisi rhoncus congue. Sed quis neque non tortor viverra hendrerit. Sed sed elementum ligula. Praesent elementum nisi enim, consequat pharetra eros bibendum sed. Sed non bibendum libero. Nulla a quam ante. Nam at orci urna.</p>

      <p>Suspendisse mattis nisi interdum velit tincidunt lacinia. Suspendisse luctus urna nec lobortis laoreet. Donec sed accumsan ipsum. Vivamus ut eleifend nibh. Fusce sit amet ullamcorper erat. Aliquam accumsan auctor metus, quis tincidunt nunc volutpat nec. Vivamus vulputate est in blandit aliquam. Donec mi ante, efficitur sit amet posuere eu, molestie et purus.</p>

      <p>Aliquam eget ante quis nisl rutrum sollicitudin. Aliquam vestibulum, dolor ac mattis aliquam, ipsum nibh commodo elit, quis blandit elit erat vitae est. Nam lobortis enim vel accumsan feugiat. Cras rutrum interdum metus, in dignissim velit sollicitudin eu. Nullam id ipsum vel felis tristique egestas quis eget est. Nunc non justo et arcu porta consequat et ac elit. Phasellus ut eleifend neque, non vulputate sem. Ut leo eros, fermentum ut orci scelerisque, scelerisque dignissim nisi. Sed lobortis purus ligula, eu molestie dui varius vel.</p>

      <p>Donec id faucibus purus. Nulla non purus sit amet augue blandit dignissim. Suspendisse viverra turpis turpis, eu lacinia ex sagittis nec. Sed et nibh ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a purus tempus, consectetur quam in, lacinia sem. Praesent vitae metus faucibus, finibus lorem non, pulvinar neque. Integer ornare eget mauris a malesuada. Suspendisse non fermentum turpis. Nam sit amet sapien vestibulum tortor laoreet placerat in semper arcu. Etiam est neque, commodo et imperdiet eget, fringilla id nulla. Etiam vitae fringilla leo, ut tempus lectus.</p>

      <p>Sed et risus lobortis, accumsan mauris ut, bibendum nisi. Proin molestie bibendum tellus, sit amet pharetra nulla sollicitudin a. Nulla eget ullamcorper diam, id consectetur eros. Donec ac rutrum mi. Donec suscipit augue ac quam ultricies suscipit. Fusce blandit consequat arcu. Nam gravida ligula et convallis tempus.</p>

      <p>Pellentesque facilisis euismod laoreet. Curabitur tellus elit, vulputate a ligula quis, varius tempus justo. Nam cursus, tortor at vestibulum feugiat, justo justo elementum metus, nec tristique neque velit pharetra velit. Curabitur quam libero, fermentum quis efficitur quis, ornare eget ante. Vivamus venenatis tortor in ante dapibus pellentesque. Phasellus ut nulla ut sem tincidunt lobortis quis vitae turpis. Donec sodales, tellus vel pulvinar dapibus, erat nisi feugiat dolor, eu faucibus nulla turpis ut tortor. Mauris mollis, massa id tristique luctus, lorem nibh venenatis nisi, eu finibus nunc sem vitae dui. Nam ut venenatis magna, facilisis sagittis magna. Donec non interdum nibh. Integer commodo, sem quis placerat cursus, tellus erat vestibulum magna, non semper dui ipsum non mauris. Maecenas volutpat felis dolor, consequat aliquam eros facilisis sodales. Nullam iaculis finibus quam, sit amet ultrices tellus vestibulum eget.</p>

      <p>Duis dictum felis vel lorem tempor, eu ultricies erat dapibus. Duis elit orci, pretium in finibus sit amet, pretium at velit. Sed tincidunt sem non vulputate bibendum. Donec eleifend aliquet enim ac dapibus. Suspendisse iaculis nisi quis justo imperdiet, eget efficitur felis tristique. Aliquam viverra ante ac metus feugiat, a tempus lorem luctus. In hac habitasse platea dictumst. Mauris a quam leo.</p>

      <p>Nam aliquet pulvinar velit, sed imperdiet nisl pulvinar a. Morbi porta varius quam, nec aliquet nisi egestas nec. Ut lobortis vehicula metus in pharetra. Sed sed vulputate velit. Donec ultricies mauris at magna tempus consectetur. Morbi ac dapibus enim, fringilla feugiat metus. Maecenas vestibulum, libero nec imperdiet interdum, turpis metus ullamcorper libero, quis maximus neque diam sit amet sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In a purus consequat, bibendum nunc sagittis, interdum augue. Sed interdum aliquam velit, sit amet tincidunt metus euismod id.</p>

      <p>Proin ut pretium ligula. Etiam sit amet eleifend leo. Curabitur feugiat dapibus tortor ac condimentum. Proin quis porta nunc. Mauris in iaculis est. Duis consectetur, magna non malesuada tempus, neque orci lobortis massa, at mollis massa neque a lacus. Vivamus ac mauris sed ligula vestibulum placerat. Morbi vitae condimentum sem. Morbi fermentum feugiat nulla nec porta. Aliquam ornare at ex eu congue.</p>

      <p>Nam mauris nulla, vehicula eu mi a, porta scelerisque tellus. Pellentesque vehicula iaculis blandit. Sed pulvinar auctor odio. Praesent venenatis ante sit amet neque lobortis, sit amet fermentum mi faucibus. Sed vel porttitor augue. Donec ultrices pellentesque laoreet. Suspendisse sed purus est. Sed tempus lacus tincidunt dolor scelerisque semper. Suspendisse eu tempus urna. Nam vitae ligula consectetur, viverra leo a, molestie lectus.</p>

      <p>Proin cursus arcu sed sem posuere, semper rutrum orci placerat. Integer commodo ipsum quis orci imperdiet euismod. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec et erat non ante bibendum viverra. Nullam sit amet accumsan mi. Donec a ligula et tellus aliquam euismod quis tempus felis. Quisque vel nibh iaculis, eleifend massa vitae, laoreet metus. Nunc quis nisi metus. Curabitur ac felis leo. Ut rhoncus, nibh nec elementum semper, ligula sem imperdiet magna, ac euismod felis nulla tempus ligula. Sed pharetra nulla in elit ullamcorper scelerisque. Duis purus est, auctor et dictum at, fringilla et dui. Etiam imperdiet finibus facilisis. Donec vestibulum nibh non massa pulvinar tempor. Aliquam euismod maximus tellus porttitor auctor.</p>

      <p>Proin feugiat, erat eget molestie rutrum, est velit congue mauris, vitae posuere velit ipsum in ante. In egestas placerat ex, sed tempor leo. Cras vel suscipit est. Cras convallis erat vitae felis bibendum posuere. Quisque ornare maximus nisl vitae dignissim. Quisque quis blandit dui. Vestibulum at egestas erat. Curabitur egestas enim nisi, ac ultrices ligula bibendum quis. Proin congue feugiat odio, eu cursus lectus faucibus eu. Morbi quis purus eu mi vestibulum faucibus et id purus.</p>

      <p>Nunc et mi bibendum nibh tristique iaculis. Sed sollicitudin ornare imperdiet. Mauris aliquet vehicula est, nec laoreet neque posuere ac. Nullam a ornare nunc. Ut faucibus lectus a urna pellentesque, ut mollis felis molestie. Vestibulum vulputate mauris ut molestie egestas. Suspendisse posuere eget est et tincidunt. Nunc nec feugiat orci. Donec enim massa, faucibus vel tellus pulvinar, semper sagittis diam.</p>
    </div>
  `,
})
export class AppComponent {
  title = 'mtx-bot-test';
}
